-- shard2 database
CREATE DATABASE IF NOT EXISTS shard2;
-- bottom half shard table of biz_tbl
CREATE TABLE IF NOT EXISTS shard2.biz_tbl_4 (
    id bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'physical id',
    biz_id bigint(19) NOT NULL COMMENT 'shard by biz id',
    t_bit bit NOT NULL DEFAULT 0 COMMENT 'bit type',
    t_tinyint_unsigned tinyint(3) unsigned DEFAULT 0 COMMENT 'unsigned tinyint type',
    t_smallint smallint(6) DEFAULT 0 COMMENT 'smallint type',
    t_smallint_unsigned smallint(5) unsigned DEFAULT 0 COMMENT 'unsigned smallint type',
    t_mediumint mediumint(8) DEFAULT 0 COMMENT 'mediumint type',
    t_mediumint_unsigned mediumint(8) unsigned DEFAULT 0 COMMENT 'unsigned mediumint type',
    t_int int(11) DEFAULT 0 COMMENT 'int type',
    t_int_unsigned int(10) DEFAULT 0 COMMENT 'unsigned int type',
    t_decimal decimal(14, 3) DEFAULT 0.000 COMMENT 'decimal type',
    t_year year DEFAULT '2020' COMMENT 'year type',
    t_date date DEFAULT '2020-01-01' COMMENT 'date type',
    t_time time DEFAULT '23:59:59' COMMENT 'time type',
    t_timestamp timestamp DEFAULT '2020-01-01 23:59:59' COMMENT 'timestamp type',
    t_char char(4) DEFAULT 'abcd' COMMENT 'char type',
    t_varchar varchar(32) DEFAULT '' COMMENT 'varchar type',
    t_binary binary(8) COMMENT 'binary type',
    t_varbinary varbinary(32) DEFAULT '' COMMENT 'varbinary type',
    t_tinyblob tinyblob COMMENT 'tinyblob type',
    t_blob blob COMMENT 'blob type',
    t_mediumblob mediumblob COMMENT 'medium blob type',
    t_longblob longblob COMMENT 'long blob type',
    t_tinytext tinytext COMMENT 'tinytext type',
    t_text text COMMENT 'text type',
    t_mediumtext mediumtext COMMENT 'medium text type',
    t_longtext longtext COMMENT 'long text type',
    t_json json COMMENT 'json type',
    t_geometry geometry COMMENT 'geometry type',
    is_deleted tinyint(4) NOT NULL DEFAULT 0 COMMENT 'soft delete flag',
    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    PRIMARY KEY(id),
    KEY ix_biz_id(biz_id),
    KEY ix_created_at(created_at),
    KEY ix_updated_at(updated_at)
);
CREATE TABLE IF NOT EXISTS shard2.biz_tbl_5 (
    id bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'physical id',
    biz_id bigint(19) NOT NULL COMMENT 'shard by biz id',
    t_bit bit NOT NULL DEFAULT 0 COMMENT 'bit type',
    t_tinyint_unsigned tinyint(3) unsigned DEFAULT 0 COMMENT 'unsigned tinyint type',
    t_smallint smallint(6) DEFAULT 0 COMMENT 'smallint type',
    t_smallint_unsigned smallint(5) unsigned DEFAULT 0 COMMENT 'unsigned smallint type',
    t_mediumint mediumint(8) DEFAULT 0 COMMENT 'mediumint type',
    t_mediumint_unsigned mediumint(8) unsigned DEFAULT 0 COMMENT 'unsigned mediumint type',
    t_int int(11) DEFAULT 0 COMMENT 'int type',
    t_int_unsigned int(10) DEFAULT 0 COMMENT 'unsigned int type',
    t_decimal decimal(14, 3) DEFAULT 0.000 COMMENT 'decimal type',
    t_year year DEFAULT '2020' COMMENT 'year type',
    t_date date DEFAULT '2020-01-01' COMMENT 'date type',
    t_time time DEFAULT '23:59:59' COMMENT 'time type',
    t_timestamp timestamp DEFAULT '2020-01-01 23:59:59' COMMENT 'timestamp type',
    t_char char(4) DEFAULT 'abcd' COMMENT 'char type',
    t_varchar varchar(32) DEFAULT '' COMMENT 'varchar type',
    t_binary binary(8) COMMENT 'binary type',
    t_varbinary varbinary(32) DEFAULT '' COMMENT 'varbinary type',
    t_tinyblob tinyblob COMMENT 'tinyblob type',
    t_blob blob COMMENT 'blob type',
    t_mediumblob mediumblob COMMENT 'medium blob type',
    t_longblob longblob COMMENT 'long blob type',
    t_tinytext tinytext COMMENT 'tinytext type',
    t_text text COMMENT 'text type',
    t_mediumtext mediumtext COMMENT 'medium text type',
    t_longtext longtext COMMENT 'long text type',
    t_json json COMMENT 'json type',
    t_geometry geometry COMMENT 'geometry type',
    is_deleted tinyint(4) NOT NULL DEFAULT 0 COMMENT 'soft delete flag',
    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    PRIMARY KEY(id),
    KEY ix_biz_id(biz_id),
    KEY ix_created_at(created_at),
    KEY ix_updated_at(updated_at)
);
CREATE TABLE IF NOT EXISTS shard2.biz_tbl_6 (
    id bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'physical id',
    biz_id bigint(19) NOT NULL COMMENT 'shard by biz id',
    t_bit bit NOT NULL DEFAULT 0 COMMENT 'bit type',
    t_tinyint_unsigned tinyint(3) unsigned DEFAULT 0 COMMENT 'unsigned tinyint type',
    t_smallint smallint(6) DEFAULT 0 COMMENT 'smallint type',
    t_smallint_unsigned smallint(5) unsigned DEFAULT 0 COMMENT 'unsigned smallint type',
    t_mediumint mediumint(8) DEFAULT 0 COMMENT 'mediumint type',
    t_mediumint_unsigned mediumint(8) unsigned DEFAULT 0 COMMENT 'unsigned mediumint type',
    t_int int(11) DEFAULT 0 COMMENT 'int type',
    t_int_unsigned int(10) DEFAULT 0 COMMENT 'unsigned int type',
    t_decimal decimal(14, 3) DEFAULT 0.000 COMMENT 'decimal type',
    t_year year DEFAULT '2020' COMMENT 'year type',
    t_date date DEFAULT '2020-01-01' COMMENT 'date type',
    t_time time DEFAULT '23:59:59' COMMENT 'time type',
    t_timestamp timestamp DEFAULT '2020-01-01 23:59:59' COMMENT 'timestamp type',
    t_char char(4) DEFAULT 'abcd' COMMENT 'char type',
    t_varchar varchar(32) DEFAULT '' COMMENT 'varchar type',
    t_binary binary(8) COMMENT 'binary type',
    t_varbinary varbinary(32) DEFAULT '' COMMENT 'varbinary type',
    t_tinyblob tinyblob COMMENT 'tinyblob type',
    t_blob blob COMMENT 'blob type',
    t_mediumblob mediumblob COMMENT 'medium blob type',
    t_longblob longblob COMMENT 'long blob type',
    t_tinytext tinytext COMMENT 'tinytext type',
    t_text text COMMENT 'text type',
    t_mediumtext mediumtext COMMENT 'medium text type',
    t_longtext longtext COMMENT 'long text type',
    t_json json COMMENT 'json type',
    t_geometry geometry COMMENT 'geometry type',
    is_deleted tinyint(4) NOT NULL DEFAULT 0 COMMENT 'soft delete flag',
    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    PRIMARY KEY(id),
    KEY ix_biz_id(biz_id),
    KEY ix_created_at(created_at),
    KEY ix_updated_at(updated_at)
);
CREATE TABLE IF NOT EXISTS shard2.biz_tbl_7 (
    id bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'physical id',
    biz_id bigint(19) NOT NULL COMMENT 'shard by biz id',
    t_bit bit NOT NULL DEFAULT 0 COMMENT 'bit type',
    t_tinyint_unsigned tinyint(3) unsigned DEFAULT 0 COMMENT 'unsigned tinyint type',
    t_smallint smallint(6) DEFAULT 0 COMMENT 'smallint type',
    t_smallint_unsigned smallint(5) unsigned DEFAULT 0 COMMENT 'unsigned smallint type',
    t_mediumint mediumint(8) DEFAULT 0 COMMENT 'mediumint type',
    t_mediumint_unsigned mediumint(8) unsigned DEFAULT 0 COMMENT 'unsigned mediumint type',
    t_int int(11) DEFAULT 0 COMMENT 'int type',
    t_int_unsigned int(10) DEFAULT 0 COMMENT 'unsigned int type',
    t_decimal decimal(14, 3) DEFAULT 0.000 COMMENT 'decimal type',
    t_year year DEFAULT '2020' COMMENT 'year type',
    t_date date DEFAULT '2020-01-01' COMMENT 'date type',
    t_time time DEFAULT '23:59:59' COMMENT 'time type',
    t_timestamp timestamp DEFAULT '2020-01-01 23:59:59' COMMENT 'timestamp type',
    t_char char(4) DEFAULT 'abcd' COMMENT 'char type',
    t_varchar varchar(32) DEFAULT '' COMMENT 'varchar type',
    t_binary binary(8) COMMENT 'binary type',
    t_varbinary varbinary(32) DEFAULT '' COMMENT 'varbinary type',
    t_tinyblob tinyblob COMMENT 'tinyblob type',
    t_blob blob COMMENT 'blob type',
    t_mediumblob mediumblob COMMENT 'medium blob type',
    t_longblob longblob COMMENT 'long blob type',
    t_tinytext tinytext COMMENT 'tinytext type',
    t_text text COMMENT 'text type',
    t_mediumtext mediumtext COMMENT 'medium text type',
    t_longtext longtext COMMENT 'long text type',
    t_json json COMMENT 'json type',
    t_geometry geometry COMMENT 'geometry type',
    is_deleted tinyint(4) NOT NULL DEFAULT 0 COMMENT 'soft delete flag',
    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    PRIMARY KEY(id),
    KEY ix_biz_id(biz_id),
    KEY ix_created_at(created_at),
    KEY ix_updated_at(updated_at)
);