package me.ele.jarch.athena.netty.state;

public enum SESSION_STATUS {
    CLIENT_FAKE_HANDSHAKE, CLIENT_FAKE_AUTH, QUERY_ANALYZE, FAKE_SQL, QUERY_HANDLE, QUERY_RESULT, FIELDS_RESULT, GRAY_QUERY_HANDLE, GRAY_RESULT, QUIT, BATCH_ANALYZE, BATCH_HANDLE, BATCH_RESULT, BATCH_QUIT
}
